name: conda-publish-env
dependencies: 
  - python
  - setuptools
  - python
  - future
  - numpy>=0.11
  - pandas
  - scikit-learn>=0.19.0
  - scipy>=0.17.0
  - pillow>=6.2.0
  - pytorch>=1.0.0
  - torchvision
